### ISSUE TITLE
Especialización en Git

### ISSUE THREAD

**Issue by gfsol** [PabloJimm/ISO2-MetaData-Management-Explorer-C0.04#2]
Alejandro Muñoz Gonzalez y Daniel Sanchez Rodriguez se encargarán de especializarse en git para posteriormente enseñar a los demás compañeros el uso de la herramienta

**Comment by PabloJimm** [comment]
La especialización se llevo a cabo durante la [reunión #3](https://github.com/PabloJimm/ISO2-MetaData-Management-Explorer-C0.04/wiki/Actas#reuni%C3%B3n-3) el 14/10/2024.
