### ISSUE TITLE
Especialización en Maven

### ISSUE THREAD

**Issue by gfsol** [PabloJimm/ISO2-MetaData-Management-Explorer-C0.04#3]
Alejandro Rodríguez Saludador y Jun Hao Lin se encargarán de especializarse en git para posteriormente enseñar a los demás compañeros el uso de la herramienta.

**Comment by PabloJimm** [comment]
La especialización se llevo acabo durante la reunión #4 el 6/11/2024, en ella se configuro el maven de todos los participantes y se explico su funcionamiento.
