### ISSUE TITLE
Creación de diagrama de casos uso.

### ISSUE THREAD

**Issue by gfsol** [PabloJimm/ISO2-MetaData-Management-Explorer-C0.04#5]
Se deberá realizar el diagrama de casos de uso del proyecto.

**Comment by PabloJimm** [comment]
La tarea esta terminada, esta tarea es susceptible a cambios. En el caso de haya cambios se actualizara el documento. El tiempo total ha sido de 1h y 35min

**Comment by PabloJimm** [comment]
Se ha subido el archivo a el apartado de la Wiki [Diagrama De casos de Uso](https://github.com/PabloJimm/ISO2-MetaData-Management-Explorer-C0.04/wiki/Diagrama-de-Casos-de-Uso).
